# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(n_max = 100L) {
    .Call('asantest_test', PACKAGE = 'asantest', n_max)
}

